### ISSUE TITLE
Export This Result: Exports all records

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#847]
When you select a single site, and choose to export via csv ... it exports all sites. 

Expected: That it would export only the site opened.

**Comment by ggiraldez** [comment]
I think this is a UI/UX issue. The export links refer to the filtered subset of all the sites in a collection, but due to the position of the control in the UI, when navigating to a single site, it looks like it should only export the currently visible site.

Either change the functionality or move the export buttons out of the navigation frame (eg. below the search description).
